CREATE TABLE time_slots (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    expert_id BIGINT NOT NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'AVAILABLE',
    start_time TIMESTAMP NOT NULL,
    end_time TIMESTAMP NOT NULL,
    version BIGINT DEFAULT 0,
    created_at TIMESTAMP NULL DEFAULT NULL,
    CONSTRAINT fk_time_slots_expert FOREIGN KEY (expert_id) REFERENCES experts(id),
    CONSTRAINT chk_time_slots_status CHECK (status IN ('AVAILABLE', 'LOCKED', 'BOOKED'))
);

CREATE INDEX idx_time_slots_expert_start ON time_slots(expert_id, start_time);
