spring.application.name=patient_booking

spring.security.oauth2.resourceserver.jwt.issuer-uri=https://accounts.google.com

app.google.client-id=YOUR_GOOGLE_CLIENT_ID
app.cors.allowed-origins=http://localhost:3000
